### ISSUE TITLE
Small changes to the module to make it compatible with the steady flow and time dep examples

### ISSUE THREAD

**Issue by jbisits** [jbisits/QG_tracer_advection#12]
@navidcy, I am sorry I did not do this in a pull request, I was working by accident on the master and as nothing really changed I committed it but am happy to alter it if you would like me to. I have made some examples for the steady flow and time dependent flow tracer advection (ie examples of the `TracerAdvectionDiffusion` module that you had already written) and added these to the list of files. Both have directions as to how to run them using the `TracerAdvectionDiffusion` module in the script. I can move these to the `PassiveTracerFlows` or just get rid of them all together if you would prefer. I just put them there to show everything the module can do. I had to modify some small things in the `TracerAdvDiff_QG` module to make the steady flow and time dep tracer advection problems run. It was just some variable names (in equation for both it was called `LC` which I changed to `L`) that were incorrect or from an old version and making sure that when there is only one layer the `vars` are initialised to be size `(nx, ny)` and not `(nx, ny, 1)`. Again apologies this was not in a pull request!

**Comment by navidcy** [comment]
No worries!
